// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzMiBDzyGK0GcIDaBVQk4LeKByn8vp8Dk',
    appId: '1:514037743080:web:39fa92c5bb1d9ad025f85d',
    messagingSenderId: '514037743080',
    projectId: 'everqpid-2601a',
    authDomain: 'everqpid-2601a.firebaseapp.com',
    storageBucket: 'everqpid-2601a.firebasestorage.app',
    measurementId: 'G-P9X3TZHREE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjC4wORUB4mwLjrYRBYtzqub5BPJVu2TQ',
    appId: '1:514037743080:android:f71b81dc1daf137725f85d',
    messagingSenderId: '514037743080',
    projectId: 'everqpid-2601a',
    storageBucket: 'everqpid-2601a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9CiottB-wogKB36TaqVm3MF9HXHAGHw',
    appId: '1:514037743080:ios:6e6f394e9a928d1e25f85d',
    messagingSenderId: '514037743080',
    projectId: 'everqpid-2601a',
    storageBucket: 'everqpid-2601a.firebasestorage.app',
    androidClientId:
        '514037743080-u6h36vi7qmlhh3if0fq7drfa4jevrt53.apps.googleusercontent.com',
    iosClientId:
        '514037743080-61ssng8ul1n8bv5rgbokn6ir2k0dtf1o.apps.googleusercontent.com',
    iosBundleId: 'com.everqpid.customerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs9CiottB-wogKB36TaqVm3MF9HXHAGHw',
    appId: '1:514037743080:ios:d3c342957100046d25f85d',
    messagingSenderId: '514037743080',
    projectId: 'everqpid-2601a',
    storageBucket: 'everqpid-2601a.firebasestorage.app',
    iosBundleId: 'com.example.everqpidapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzMiBDzyGK0GcIDaBVQk4LeKByn8vp8Dk',
    appId: '1:514037743080:web:d6e5ee161b70e88d25f85d',
    messagingSenderId: '514037743080',
    projectId: 'everqpid-2601a',
    authDomain: 'everqpid-2601a.firebaseapp.com',
    storageBucket: 'everqpid-2601a.firebasestorage.app',
    measurementId: 'G-HFQS6V0V5S',
  );
}
